'use strict'
import "@babel/polyfill";
import './modules/polyfills';
import phoneNumbers from './modules/phoneNumbers';
import popups from './modules/popups';
import maskForPhones from './modules/maskForPhones';
import prompts from './modules/prompts';
import typesOfRepair from './modules/typesOfRepair';
import portfolio from './modules/portfolio';
import documents from './modules/documents';
import documentPopup from './modules/documentPopup';
import accordion from './modules/accordion';
import problems from './modules/problems';
import designSolutions from './modules/designSolutions';
import consultation from './modules/consultation';
import reviews from './modules/reviews';
import howWeWork from './modules/howWeWork';
import ourPartners from './modules/ourPartners';
import sendForms from './modules/sendForms';
import serviceList from './modules/serviceList';
import checkName from './modules/checkName';
import servicesSlider from './modules/servicesSlider';
import scrollMenu from './modules/scrollMenu';

phoneNumbers();
popups();
maskForPhones();
prompts();
typesOfRepair();
portfolio();
documents();
documentPopup();
accordion();
problems();
designSolutions();
consultation();
reviews();
howWeWork();
ourPartners();
sendForms();
serviceList();
servicesSlider();
checkName();
scrollMenu();